--
-- PostgreSQL database dump
--

-- Dumped from database version 14.0
-- Dumped by pg_dump version 14.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: tache; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tache (
    id bigint NOT NULL,
    description character varying(255),
    statut character varying(255),
    titre character varying(255),
    date_creation date,
    date_echeance date,
    priorite character varying(255),
    responsable character varying(255),
    CONSTRAINT tache_priorite_check CHECK (((priorite)::text = ANY ((ARRAY['BASSE'::character varying, 'MOYENNE'::character varying, 'HAUTE'::character varying])::text[]))),
    CONSTRAINT tache_statut_check CHECK (((statut)::text = ANY ((ARRAY['A_FAIRE'::character varying, 'EN_COURS'::character varying, 'TERMINEE'::character varying])::text[])))
);


ALTER TABLE public.tache OWNER TO postgres;

--
-- Name: tache_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tache ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tache_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: tache; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tache (id, description, statut, titre, date_creation, date_echeance, priorite, responsable) FROM stdin;
12	Créer un guide complet d'utilisation de l'application	EN_COURS	Préparer la documentation utilisateur	2025-04-14	2025-05-15	HAUTE	Bob
13	Ajout de nouvelles colonnes pour le suivi des statuts	TERMINEE	Mise à jour de la base de données	2025-04-14	2025-05-10	MOYENNE	Claire
14	Refactorisation des services et suppression du code mort	EN_COURS	Nettoyage du code	2025-04-14	2025-05-15	MOYENNE	David
15	Évaluer l'avancement des tâches chaque vendredi	A_FAIRE	Revue hebdomadaire	2025-04-14	2025-04-19	HAUTE	Emma
11	Maîtriser les conceptes fondamentaux	EN_COURS	Apprende spring boot	2025-04-14	2025-05-30	MOYENNE	Jean
16	Créer les slides pour la présentation client de la semaine prochaine.	EN_COURS	Préparer la présentation	2025-04-14	2025-04-17	HAUTE	Alice
\.


--
-- Name: tache_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tache_id_seq', 16, true);


--
-- Name: tache tache_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tache
    ADD CONSTRAINT tache_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

